/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5b40e016-404b-4542-83f3-7991e8246226",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Hx6qidued",
    "aws_user_pools_web_client_id": "10vbsr3i5145vf3hle4rs7f3d0",
    "oauth": {}
};


export default awsmobile;
