/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f0161e7e-4d23-45c5-8638-28165407ed16",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VG4YNVRME",
    "aws_user_pools_web_client_id": "27u7jtv73c5a8id49024bai2bl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ntqf2byhpvbnxiqptpfozfwppm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
