/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:9aec2e63-4e2c-48c3-895a-e8c866d51628",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_2g8Yqcow4",
  aws_user_pools_web_client_id: "2dffnl6eks4avec7lk62tloc63",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://ngclfjpphbembonemqjba6iynu.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-fakeApiId123456",
};

export default awsmobile;
